config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :registrations => 'registrations',
    ## :sessions => 'users/sessions'
  }

  root to: "pages#onboarding", as: 'onboarding'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  mount ActionCable.server => '/cable'

  # Home routes
  get 'home', to: 'pages#home', as: 'home'
  get 'slide1', to: 'pages#slide1', as: 'slide1'
  get 'slide2', to: 'pages#slide2', as: 'slide2'
  get 'slide3', to: 'pages#slide3', as: 'slide3'

  # Horses routes
  get 'horses/:id/edit', to: 'horses#edit', as: "horse_edit"
  get 'horses', to: 'horses#index'
  get 'potros', to: 'horses#potros', as: 'potros'
  get 'horses/filtros', to: 'horses#filtros', as: :horses_filtros
  post 'horses/aplicar_filtros', to: 'horses#aplicarfiltros', as: :horses_aplicar_filtros
  get 'horses/resultados', to: 'horses#resultados', as: :horses_results
  get 'horses/new', to: 'horses#new', as: 'horse_new'
  get 'horses/:id', to: 'horses#show', as: "horse_show"
  post 'horses', to: 'horses#create'
  put 'horses/:id', to: 'horses#update', as: "horse_update"
  delete 'horses/:id', to: 'horses#destroy', as: :horses_destroy
  delete 'horses/:id/delete_video', to: 'horses#delete_video', as: :delete_video_horse

  # Auctions routes
  get 'active_auctions', to: 'auctions#active_auctions', as: 'active_auctions'
  get 'next_acutions', to: 'auctions#next_auctions', as: 'next_auctions'
  get 'auctions/new', to: 'auctions#new'
  post 'auctions', to: 'auctions#create'
  get 'auctions/:id', to: 'auctions#show', as: 'auction'
  get 'auctions/:id/edit', to: 'auctions#edit'
  put 'auctions/:id', to: 'auctions#update'
  delete 'auctions/:id', to: 'auctions#destroy', as: :auction_destroy

  # Lotes views
  get 'auctions/:id/lotes', to: 'lotes#index'
  get 'auctions/:id/lotes/:id', to: 'lotes#show'
  get 'auctions/:id/lotes/new', to: 'lotes#new'
  post 'auctions/:id/lotes', to: 'lotes#create'
  get 'auctions/:id/lotes/:id/edit', to: 'lotes#edit'
  put 'auctions/:id/lotes/:id', to: 'lotes#update'

  # Menu views
  get 'search', to: 'pages#search', as: 'search'
  get 'add', to: 'pages#add', as: 'add'

  # Profile views
  get 'perfiles', to: 'profiles#profile_index', as: 'profile_index'
  get 'perfiles/:id', to: 'profiles#show', as: 'profile_show'
  resources :users do
    resources :reviews, only: :create
    end
  get 'favoritos/caballos', to: 'profiles#favorite_caballos', as: 'profile_favorite_caballos'
  get 'favoritos/remates', to: 'profiles#favorite_remates', as: 'profile_favorite_remates'
  get 'notificationes', to: 'profiles#notification', as: 'profile_notification'
  get 'mis_publicaciones/caballos', to: 'profiles#publication_caballos', as: 'profile_publication_caballos'
  get 'mis_publicaciones/remates', to: 'profiles#publication_remates', as: 'profile_publication_remates'
  post 'favorite_horse/:horse', to: 'favorites#update_horse', as: 'favorite_horse'
  post 'favorite_auction/:auction', to: 'favorites#update_auction', as: 'favorite_auction'
  get 'gracias_registo', to: 'pages#gracias', as: 'registro_gracias'

  # Reviews routes
  get 'approve_review/:id', to: 'reviews#approve', as: 'approve_review'
  get 'disapprove_review/:id', to: 'reviews#disapprove', as: 'disapprove_review'
  delete 'reviews/:id', to: 'reviews#destroy', as: 'review_destroy'

  # Conversation routes
  get 'conversaciones/activas', to: 'conversations#conversaciones_activas', as: 'conversaciones_activas'
  get 'conversaciones/archivadas', to: 'conversations#conversaciones_archivadas', as: 'conversaciones_archivadas'
  post 'conversaciones', to: 'conversations#create', as: 'conversaciones_create'
  get 'conversaciones/:id', to: 'conversations#show', as: 'conversacion_show'
  put 'conversaciones/:id/archivar', to: 'conversations#archivar', as: 'conversacion_archivar'
  put 'conversaciones/:id/desarchivar', to: 'conversations#desarchivar', as: 'conversacion_desarchivar'
  delete 'conversaciones/:id', to: 'conversations#destroy', as: 'conversacion_destroy'

  # Messages routes
  post 'mensajes', to: 'messages#create', as: 'conversation_messages'
  get 'favorite_horse/:id', to: 'favorites#delete_horse', as: 'favorite_delete_horse'
  get 'favorite_auction/:id', to: 'favorites#delete_auction', as: 'favorite_delete_auction'

  # Contact routes
  get '/contact', to: 'contact#index'
  post '/send_message', to: 'contact#send_message'

  # Admin routes
  get 'admin/contact/pending', to: 'admin#help_contact_pending', as: 'admin_help_contact_pending'
  get 'admin/contact/resolved', to: 'admin#help_contact_resolved', as: 'admin_help_contact_resolved'
  put 'admin/contact/:id', to: 'admin#help_update', as: 'admin_help_update'
  get 'admin/reviews/pending', to: 'admin#reviews_pending', as: 'admin_reviews_pending'
  get 'admin/reviews/resolved', to: 'admin#reviews_resolved', as: 'admin_reviews_resolved'
  
  # Pub routes
  get 'pubs', to: 'pubs#index'
  post 'pubs', to: 'pubs#create'
  post 'pubs/delete_pub_img', to: 'pubs#delete_pub_img', as: 'delete_pub_img'
  post 'pubs/delete_pub_video', to: 'pubs#delete_pub_video', as: 'delete_pub_video'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[show]
  before_action :sub_links

  def profile_index
    @section_title = "Mi perfil"
  end

  def show
    @user = User.find(params[:id])
    @horses = Horse.where(user_id: @user.id)
    @section_title = @user.nombre + " " + @user.apellido
    @review = Review.new
    @reviews = Review.where(user: current_user)
    @conversation = Conversation.new
  end

  def favorite_caballos
    @section_title = "Favoritos"
    @horses = Horse.all.where(id: Favorite.where(user_id: current_user).pluck(:horse_id))
  end

  def favorite_remates
    @section_title = "Favoritos"
    @auctions = Auction.all.where(id: Favorite.where(user_id: current_user).pluck(:auction_id))
  end

  def notification
    @section_title = "Notificaciones"

    @notifications_mensajes = Notification.joins(:message)
      .where(tipo: "mensaje")
      .where.not(messages: { user_id: current_user.id })

    # @notifications_favoritos_horses = Notification.joins(favorite: { horse: :user })
    #   .where(tipo: "favorite_horse")
    #   .where(users: { id: current_user.id })
    #   .where.not(user_id: current_user.id)

    # @notifications_favoritos_auctions = Notification.joins(favorite: { auction: :user })
    #   .where(tipo: "favorite_auction")
    #   .where(users: { id: current_user.id })
    #   .where.not(user_id: current_user.id)

    @notifications_horses = Notification.joins(horse: :user)
      .where(tipo: "publication")
      .where.not(user_id: current_user.id)

      @notifications = (@notifications_mensajes + @notifications_horses)
      .uniq
      .sort_by(&:created_at)
      .reverse
  end

  def publication_caballos
    @section_title = "Mis publicaciones"
    @horses = Horse.all.where(user_id: current_user)
  end

  def publication_remates
    @section_title = "Mis publicaciones"
    @auctions = Auction.all.where(user_id: current_user)
    @auctions = @auctions.where("finish > ?", Time.now)
  end

  def sub_links
    @sub_links_publicaciones = [
      { title: "Caballos", path: profile_publication_caballos_path },
      { title: "Remates", path: profile_publication_remates_path }
    ]

    @sub_links_favoritos = [
      { title: "Caballos", path: profile_favorite_caballos_path },
      { title: "Remates", path: profile_favorite_remates_path }
    ]
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
  def user_rating
    begin
    (@user.rating * 2.0).round / 2.0
    rescue
    "Sin reseñas recibidas"
    end
  end
end

app/views/profiles/_notification.html.erb
<% if notification.tipo == "publication" %>
  <div class="user d-flex justify-content-between py-3">
    <div class="d-flex">
      <div>
        <%= image_tag('profile-icon.png') %>
      </div>
      <div class="d-flex flex-column justify-content-center" style="margin-left: 1rem;">
        <span class="subtitle">
          <strong><%= User.find(notification.user_id).nombre %> <%= User.find(notification.user_id).apellido %></strong> realizó una nueva
          <%= link_to horse_show_path(notification.horse_id) do %>
            publicación.
          <% end %>
        </span>
      </div>
    </div>
    <%= image_tag('add_notification.svg') %>
  </div>
<% elsif notification.tipo == "favorite_horse" %>
  <div class="user d-flex justify-content-between py-3">
    <div class="d-flex">
      <div>
        <%= image_tag('profile-icon.png') %>
      </div>
      <div class="d-flex flex-column justify-content-center" style="margin-left: 1rem;">
        <span class="subtitle"> A
          <strong><%= User.find(notification.user_id).nombre %> <%= User.find(notification.user_id).apellido %></strong> le gustó tu
          <%= link_to horse_show_path(Favorite.find(notification.favorite_id).horse) do %>
            publicación.
          <% end %>
        </span>
      </div>
    </div>
    <%= image_tag('favorite_filled.svg') %>
  </div>
<% elsif notification.tipo == "favorite_auction" %>
  <div class="user d-flex justify-content-between py-3">
    <div class="d-flex">
      <div>
        <%= image_tag('profile-icon.png') %>
      </div>
      <div class="d-flex flex-column justify-content-center" style="margin-left: 1rem;">
        <span class="subtitle"> A
          <strong><%= User.find(notification.user_id).nombre %> <%= User.find(notification.user_id).apellido %></strong> le gustó tu
          <%= link_to auction_path(Favorite.find(notification.favorite_id).auction) do %>
            publicación.
          <% end %>
        </span>
      </div>
    </div>
    <%= image_tag('favorite_filled.svg') %>
  </div>
<% elsif notification.tipo == "mensaje" %>
  <div class="user d-flex justify-content-between py-3">
    <div class="d-flex">
      <div>
        <%= image_tag('profile-icon.png') %>
      </div>
      <div class="d-flex flex-column justify-content-center" style="margin-left: 1rem;">
        <span class="subtitle">
          Tienes un
          <%= link_to conversacion_show_path(notification.conversation_id) do %>
            mensaje
          <% end %> sin leer.
        </span>
      </div>
    </div>
    <%= image_tag('mensaje_sin_leer.svg') %>
  </div>
<% end %>

app/views/profiles/favorite_caballos.html.erb
<%= render 'sub_links' %>

<div class="container" style="margin-top: 8rem !important;">

  <span class="section-subtitle mb-3">Tus favoritos</span>

  <div class="cards mb-4 mt-3">
    <div class="row">
      <% if @horses != [] %>
        <% @horses.each do |horse| %>
          <div class="col-sm-6 col-lg-4 col-sm-12">
            <%= render 'shared/horse_card', horse: horse %>
          </div>
        <% end %>
      <% else %>
        <div class="d-flex flex-column justify-content-center align-items-center" style="height: 30vh;">
          <span>No hay favoritos guardados aun</span>
          <%= link_to home_path, class: "btn-submit mt-5 d-flex align-items-center justify-content-center" do %>
            <span>VOLVER AL INICIO</span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/favorite_remates.html.erb
<%= render 'sub_links' %>

<div class="container" style="margin-top: 8rem !important;">

  <span class="section-subtitle mb-3">Tus favoritos</span>

  <div class="cards mb-4 mt-3 row">
    <% if @auctions != [] %>
      <% @auctions.each do |auction| %>
        <div class="col-sm-6 col-lg-4 col-sm-12">
          <div class="card w-100 mb-3">

            <% if auction.photo %>
            <div class="card-image w-100 h-100 d-flex align-items-end justify-content-center" style="background-image: url('<%= cl_image_path auction.photo.key %>'); background-size: cover;">
            <% else %>
              <div class="card-image w-100 h-100 d-flex align-items-end justify-content-center" style="background-image: url('<%= image_path 'auction-logo-solo.png' %>'); background-repeat: no-repeat; background-position: center; background-size: 300px;">
            <% end %>

              <div class="nombre m-0 w-100"><span><%= auction.name.capitalize %></span></div>
            </div>

            <div class="card-content">
              <div class="p-2 d-flex">
                <div class="col-4 d-flex align-items-center">
                  <%= link_to favorite_delete_auction_path(auction.id) do %>
                    <span style="color: #838383;">ELIMINAR</span>
                  <% end %>
                </div>
                <div class="col-4 d-flex justify-content-center link align-items-center">
                  <%= link_to auction_path(auction.id) do %>
                    <span>VER MAS</span>
                  <% end %>
                </div>
                <div class="col-4 d-flex justify-content-end align-items-center pr-0">
                  <div class="d-flex align-items-center justify-content-center">
                    <%# <div data-controller="share" data-share-url-value="<%= auction_path(auction)"> %>
                      <%#= button_to image_tag('share.png'), "", data: {action: "click->share#share" }, style: "border: none; background: none; padding-bottom: 0.188rem;" %>
                      <%#= content_tag(:span, "", class:"result", data: {share_target: "result" }) %>
                    <%# </div> %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="d-flex flex-column justify-content-center align-items-center" style="height: 30vh;">
        <span>No hay favoritos guardados aun</span>
        <%= link_to home_path, class: "btn-submit mt-5 d-flex align-items-center justify-content-center" do %>
          <span>VOLVER AL INICIO</span>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/profiles/favourite_caballos.html.erb
<%= render 'sub_links' %>

<div class="container" style="margin-top: 8rem !important;">

  <span class="section-subtitle mb-3">Tus favoritos</span>

  <div class="cards mb-4 mt-3">
    <div class="row">
      <% if @horses != [] %>
        <% @horses.each do |horse| %>
          <div class="col-sm-8 col-lg-6 col-sm-12">
            <div class="card w-100 mb-3">
              <% if horse.photos.any? %>
              <div class="card-image w-100 h-100 d-flex align-items-end justify-content-center" style="background-image: url('<%= cl_image_path horse.photos.last.key %>'); background-size: cover;">
              <% else %>
              <div class="card-image w-100 h-100 d-flex align-items-end justify-content-center" style="background: grey; background-size: cover;">
              <% end %>
                <div class="nombre m-0 w-100"><span><%= horse.name %></span></div>
              </div>

              <div class="card-content">
                <div class="p-2 d-flex">
                  <div class="col-3">
                      <span style="color: #838383; margin-left: 1.563rem;">ELIMINAR</span>
                  </div>
                  <div class="col-5 d-flex justify-content-center link align-items-center">
                    <%= link_to horse_show_path(horse.id) do %>
                      <span>VER MAS</span>
                    <% end %>
                  </div>
                  <div class="col-4 d-flex justify-content-end align-items-center">
                    <div class="d-flex align-items-center justify-content-center">
                      <%= image_tag('favorite.png', style: "margin-right: 7px;") %>
                      <div data-controller="share" data-share-url-value="<%= horse_show_path(horse)%>">
                        <%= button_to image_tag('share.png'), "", data: {action: "click->share#share" }, style: "border: none; background: none; padding-bottom: 0.188rem;" %>
                        <%= content_tag(:span, "", class:"result", data: {share_target: "result" }) %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="d-flex justify-content-center align-items-center" style="height: 30vh;">
          <span>No hay favoritos guardados aun</span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/favourite_remates.html.erb
<%= render 'sub_links' %>

<div class="container" style="margin-top: 8rem !important;">

  <span class="section-subtitle mb-3">Tus favoritos</span>

  <div class="cards mb-4 mt-3 row">
    <% if @auctions != [] %>
      <% @auctions.each do |auction| %>
        <div class="col-sm-8 col-lg-6 col-sm-12">
          <div class="card w-100 mb-3">

            <% if auction.photo %>
            <div class="card-image w-100 h-100 d-flex align-items-end justify-content-center" style="background-image: url('<%= cl_image_path auction.photo.key %>'); background-size: cover;">
            <% else %>
            <div class="card-image w-100 h-100 d-flex align-items-end justify-content-center" style="background: grey; background-size: cover;">
            <% end %>

              <div class="nombre m-0 w-100"><span><%= auction.name %></span></div>
            </div>

            <div class="card-content">
              <div class="p-2 d-flex">
                <div class="col-5 p-0">
                  <%= link_to auction_destroy_path(auction.id, mis_publicaciones: "true"), data: { turbo_method: :delete } do %>
                    <span style="color: #838383; margin-left: 1.563rem;">ELIMINAR</span>
                  <% end %>
                </div>
                <div class="col-4 p-0 d-flex justify-content-center link align-items-center">
                  <%= link_to auction_path(auction.id) do %>
                    <span>VER MAS</span>
                  <% end %>
                </div>
                <div class="col-3 d-flex justify-content-end align-items-center p-0">
                  <div class="d-flex align-items-center justify-content-center">
                    <%= image_tag('favorite.png', style: "margin-right: 7px;") %>
                    <div data-controller="share" data-share-url-value="<%= auction_path(auction)%>">
                      <%= button_to image_tag('share.png'), "", data: {action: "click->share#share" }, style: "border: none; background: none; padding-bottom: 0.188rem;" %>
                      <%= content_tag(:span, "", class:"result", data: {share_target: "result" }) %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="d-flex justify-content-center align-items-center" style="height: 30vh;">
        <span>No hay favoritos guardados aun</span>
      </div>
    <% end %>
  </div>
</div>

app/views/profiles/notification.html.erb
<div class="container" style="margin-top: 4.75rem !important;">
  <!-- Content -->
  <div>
    <% if @notifications != [] %>
      <% @notifications.each do |notification| %>
          <%= render "notification", notification: notification %>
      <% end %>
    <% else %>
      <div class="d-flex flex-column justify-content-center align-items-center" style="height: 30vh;">
        <span>No hay notificaciones pendientes</span>
        <%= link_to home_path, class: "btn-submit mt-5 d-flex align-items-center justify-content-center" do %>
          <span>VOLVER AL INICIO</span>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/profiles/profile_index.html.erb
<!-- Content -->
<div class="container-categorias container-filter">
  <div class="background d-flex justify-content-center" style="background-image: url('<%= image_path 'profile-background.png' %>');">

    <div class="profile-index w-100">
      <ul class="p-0">
        <li class="py-4">
          <%= link_to edit_user_registration_path, class:"d-flex justify-content-between align-items-center" do %>
            <div class="d-flex justify-content-start align-items-center">
              <%= image_tag('mis_datos.svg', style: "height: 22px; margin-right: 14px;") %>
              <span>Mis datos</span>
            </div>
            <%= image_tag('arrow-right-white.png') %>
          <% end %>
        </li>
        <li class="py-4">
          <%= link_to profile_favorite_caballos_url, class:"d-flex justify-content-between align-items-center" do %>
            <div class="d-flex justify-content-start align-items-center">
              <%= image_tag('favorite_white_empty.svg', style: "height: 22px; margin-right: 14px;") %>
              <span>Favoritos</span>
            </div>
            <%= image_tag('arrow-right-white.png') %>
          <% end %>
        </li>
        <li class="py-4">
          <%= link_to profile_notification_path, class:"d-flex justify-content-between align-items-center" do %>
            <div class="d-flex justify-content-start align-items-center">
              <%= image_tag('mis_notificaciones.svg', style: "height: 22px; margin-right: 14px;") %>
              <span>Notificaciones</span>
            </div>
            <%= image_tag('arrow-right-white.png') %>
          <% end %>
        </li>
        <li class="py-4">
          <%= link_to profile_publication_caballos_path, class:"d-flex justify-content-between align-items-center" do %>
            <div class="d-flex justify-content-start align-items-center">
              <%= image_tag('mis_publicaciones.svg', style: "height: 22px; margin-right: 14px;") %>
              <span>Mis publicaciones</span>
            </div>
            <%= image_tag('arrow-right-white.png') %>
          <% end %>
        </li>
        <% if current_user.admin == false %>
          <li class="d-flex justify-content-between py-4">
          <%= link_to contact_path, class:"d-flex justify-content-between align-items-center" do %>
            <div class="d-flex justify-content-start align-items-center">
              <%= image_tag('ayuda.svg', style: "height: 22px; margin-right: 14px;") %>
              <span>Ayuda</span>
            </div>
            <%= image_tag('arrow-right-white.png') %>
            <% end %>
          </li>
        <% end %>
        <% if current_user.admin == true %>
          <li class="d-flex justify-content-between py-4">
            <%= link_to pubs_path, class:"d-flex justify-content-between align-items-center" do %>
              <div class="d-flex justify-content-start align-items-center">
                <%= image_tag('ayuda.svg', style: "height: 22px; margin-right: 14px;") %>
                <span>Publicidad</span>
              </div>
              <%= image_tag('arrow-right-white.png') %>
            <% end %>
          </li>
          <li class="d-flex justify-content-between py-4">
            <%= link_to admin_help_contact_pending_path, class:"d-flex justify-content-between align-items-center" do %>
              <div class="d-flex justify-content-start align-items-center">
                <%= image_tag('ayuda.svg', style: "height: 22px; margin-right: 14px;") %>
                <span>Consultas</span>
              </div>
              <%= image_tag('arrow-right-white.png') %>
            <% end %>
          </li>
          <li class="d-flex justify-content-between py-4">
            <%= link_to admin_reviews_pending_path, class:"d-flex justify-content-between align-items-center" do %>
              <div class="d-flex justify-content-start align-items-center">
                <%= image_tag('star.svg', style: "height: 22px; margin-right: 14px;") %>
                <span>Reseñas</span>
              </div>
              <%= image_tag('arrow-right-white.png') %>
            <% end %>
          </li>
        <% end %>
        <li class="py-4">
          <%= button_to(destroy_user_session_path, method: :delete, id: "logout", class:"d-flex justify-content-between m-0 w-100 align-items-center border-0 bg-transparent p-0", input_html: {class: "w-100"}) do %>
            <div class="d-flex justify-content-start align-items-center">
              <%= image_tag('cerrar_sesion.svg', style: "height: 22px; margin-right: 14px;") %>
              <span>Cerrar Sesion</span>
            </div>
            <%= image_tag('arrow-right-white.png') %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

<script>
  confirmLogout = (e) => {
    const result = window.confirm("¿Estás seguro que deseas cerrar sesión?");
    if (result) {
      return true;
    } else {
      e.preventDefault();
      return false;
    }
  }
  document.getElementById("logout").addEventListener("click", confirmLogout);
</script>

app/views/profiles/publication_remates.html.erb
<%= render 'sub_links' %>

<div class="container" style="margin-top: 8rem !important;">

  <div class="cards mb-4 mt-3 row">
    <% if @auctions != [] %>
      <span class="section-subtitle mb-3">Tus publicaciones activas</span>
      <% @auctions.each do |auction| %>
        <div class="col-sm-6 col-lg-4 col-sm-12">
          <div class="card w-100 mb-3">

            <% if auction.photo.key != nil %>
              <div class="card-image w-100 h-100 d-flex align-items-end justify-content-center" style="background-image: url('<%= cl_image_path auction.photo.key %>'); background-size: cover;">
            <% else %>
              <div class="card-image w-100 h-100 d-flex align-items-end justify-content-center" style="background-image: url('<%= image_path 'auction-logo-solo.png' %>'); background-repeat: no-repeat; background-position: center; background-size: 300px;">
            <% end %>

              <div class="nombre m-0 w-100"><span><%= auction.name.capitalize %></span></div>
            </div>

            <div class="card-content">
              <div class="p-2 d-flex">
                <div class="col-4 d-flex align-items-center">
                  <%= link_to auction_destroy_path(auction.id, mis_publicaciones: "true"), data: { turbo_method: :delete } do %>
                    <span style="color: #838383;">ELIMINAR</span>
                  <% end %>
                </div>
                <div class="col-4 p-0 d-flex justify-content-center link align-items-center">
                  <%= link_to auction_path(auction.id) do %>
                    <span>VER MAS</span>
                  <% end %>
                </div>
                <div class="col-4 d-flex justify-content-end align-items-center pr-0">
                  <div class="d-flex align-items-center justify-content-center">
                    <%= button_to favorite_auction_text(auction), favorite_auction_path(auction: auction), class: "auction_heart_index mx-2", remote: true %>
                    <%# <div data-controller="share" data-share-url-value="<%= auction_path(auction)"> %>
                      <%#= button_to image_tag('share.png'), "", data: {action: "click->share#share" }, style: "border: none; background: none; padding-bottom: 0.188rem;" %>
                      <%#= content_tag(:span, "", class:"result", data: {share_target: "result" }) %>
                    <%# </div> %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="d-flex flex-column justify-content-center align-items-center" style="height: 30vh;">
        <span>No hay publicaciones realizadas aun</span>
        <%= link_to home_path, class: "btn-submit mt-5 d-flex align-items-center justify-content-center" do %>
          <span>VOLVER AL INICIO</span>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<script>
  buttons = document.querySelectorAll('.auction_heart_index')
    buttons.forEach(
    function(button) {
      if (button.innerText == "fav"){
        button.innerHTML = "<i class='fa-solid fa-heart'></i>"
      } else if (button.innerText == "nofav"){
        button.innerHTML = "<i class='fa-regular fa-heart'></i>"
      }
      button.addEventListener('click', function() {
        if (button.innerHTML == `<i class="fa-solid fa-heart"></i>`) {
          button.innerHTML = `<i class="fa-regular fa-heart"></i>`
        } else if (button.innerHTML == `<i class="fa-regular fa-heart"></i>`){
          button.innerHTML = `<i class="fa-solid fa-heart"></i>`
        }
      })
    }
  )
</script>

<style>
  .auction_heart{
    border: none;
    background: none;
    padding: 0;
    color:white;
    font-size: 1.5rem;
  }

  .auction_heart_index{
    border: none;
    background: none;
    padding: 0;
    padding-top: 2px !important;
    color: #F2DA84 !important;
    font-size: 1.3rem !important;
  }

  .auction_heart_home{
    border: none;
    background: none;
    padding: 0;
    padding-top: 2px !important;
    color: #F2DA84 !important;
    font-size: 1.3rem !important;
  }
</style>