config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :registrations => 'registrations',
    ## :sessions => 'users/sessions'
  }

  root to: "pages#onboarding", as: 'onboarding'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  mount ActionCable.server => '/cable'

  # Home routes
  get 'home', to: 'pages#home', as: 'home'
  get 'slide1', to: 'pages#slide1', as: 'slide1'
  get 'slide2', to: 'pages#slide2', as: 'slide2'
  get 'slide3', to: 'pages#slide3', as: 'slide3'

  # Horses routes
  get 'horses/:id/edit', to: 'horses#edit', as: "horse_edit"
  get 'horses', to: 'horses#index'
  get 'potros', to: 'horses#potros', as: 'potros'
  get 'horses/filtros', to: 'horses#filtros', as: :horses_filtros
  post 'horses/aplicar_filtros', to: 'horses#aplicarfiltros', as: :horses_aplicar_filtros
  get 'horses/resultados', to: 'horses#resultados', as: :horses_results
  get 'horses/new', to: 'horses#new', as: 'horse_new'
  get 'horses/:id', to: 'horses#show', as: "horse_show"
  post 'horses', to: 'horses#create'
  put 'horses/:id', to: 'horses#update', as: "horse_update"
  delete 'horses/:id', to: 'horses#destroy', as: :horses_destroy
  delete 'horses/:id/delete_video', to: 'horses#delete_video', as: :delete_video_horse

  # Auctions routes
  get 'active_auctions', to: 'auctions#active_auctions', as: 'active_auctions'
  get 'next_acutions', to: 'auctions#next_auctions', as: 'next_auctions'
  get 'auctions/new', to: 'auctions#new'
  post 'auctions', to: 'auctions#create'
  get 'auctions/:id', to: 'auctions#show', as: 'auction'
  get 'auctions/:id/edit', to: 'auctions#edit'
  put 'auctions/:id', to: 'auctions#update'
  delete 'auctions/:id', to: 'auctions#destroy', as: :auction_destroy

  # Lotes views
  get 'auctions/:id/lotes', to: 'lotes#index'
  get 'auctions/:id/lotes/:id', to: 'lotes#show'
  get 'auctions/:id/lotes/new', to: 'lotes#new'
  post 'auctions/:id/lotes', to: 'lotes#create'
  get 'auctions/:id/lotes/:id/edit', to: 'lotes#edit'
  put 'auctions/:id/lotes/:id', to: 'lotes#update'

  # Menu views
  get 'search', to: 'pages#search', as: 'search'
  get 'add', to: 'pages#add', as: 'add'

  # Profile views
  get 'perfiles', to: 'profiles#profile_index', as: 'profile_index'
  get 'perfiles/:id', to: 'profiles#show', as: 'profile_show'
  resources :users do
    resources :reviews, only: :create
    end
  get 'favoritos/caballos', to: 'profiles#favorite_caballos', as: 'profile_favorite_caballos'
  get 'favoritos/remates', to: 'profiles#favorite_remates', as: 'profile_favorite_remates'
  get 'notificationes', to: 'profiles#notification', as: 'profile_notification'
  get 'mis_publicaciones/caballos', to: 'profiles#publication_caballos', as: 'profile_publication_caballos'
  get 'mis_publicaciones/remates', to: 'profiles#publication_remates', as: 'profile_publication_remates'
  post 'favorite_horse/:horse', to: 'favorites#update_horse', as: 'favorite_horse'
  post 'favorite_auction/:auction', to: 'favorites#update_auction', as: 'favorite_auction'
  get 'gracias_registo', to: 'pages#gracias', as: 'registro_gracias'

  # Reviews routes
  get 'approve_review/:id', to: 'reviews#approve', as: 'approve_review'
  get 'disapprove_review/:id', to: 'reviews#disapprove', as: 'disapprove_review'
  delete 'reviews/:id', to: 'reviews#destroy', as: 'review_destroy'

  # Conversation routes
  get 'conversaciones/activas', to: 'conversations#conversaciones_activas', as: 'conversaciones_activas'
  get 'conversaciones/archivadas', to: 'conversations#conversaciones_archivadas', as: 'conversaciones_archivadas'
  post 'conversaciones', to: 'conversations#create', as: 'conversaciones_create'
  get 'conversaciones/:id', to: 'conversations#show', as: 'conversacion_show'
  put 'conversaciones/:id/archivar', to: 'conversations#archivar', as: 'conversacion_archivar'
  put 'conversaciones/:id/desarchivar', to: 'conversations#desarchivar', as: 'conversacion_desarchivar'
  delete 'conversaciones/:id', to: 'conversations#destroy', as: 'conversacion_destroy'

  # Messages routes
  post 'mensajes', to: 'messages#create', as: 'conversation_messages'
  get 'favorite_horse/:id', to: 'favorites#delete_horse', as: 'favorite_delete_horse'
  get 'favorite_auction/:id', to: 'favorites#delete_auction', as: 'favorite_delete_auction'

  # Contact routes
  get '/contact', to: 'contact#index'
  post '/send_message', to: 'contact#send_message'

  # Admin routes
  get 'admin/contact/pending', to: 'admin#help_contact_pending', as: 'admin_help_contact_pending'
  get 'admin/contact/resolved', to: 'admin#help_contact_resolved', as: 'admin_help_contact_resolved'
  put 'admin/contact/:id', to: 'admin#help_update', as: 'admin_help_update'
  get 'admin/reviews/pending', to: 'admin#reviews_pending', as: 'admin_reviews_pending'
  get 'admin/reviews/resolved', to: 'admin#reviews_resolved', as: 'admin_reviews_resolved'
  
  # Pub routes
  get 'pubs', to: 'pubs#index'
  post 'pubs', to: 'pubs#create'
  post 'pubs/delete_pub_img', to: 'pubs#delete_pub_img', as: 'delete_pub_img'
  post 'pubs/delete_pub_video', to: 'pubs#delete_pub_video', as: 'delete_pub_video'

end

app/views/admin/_sub_links.html.erb
<%# Setear @sub_links => desde controller %>
<div class="sub-links-section">
  <% if params[:action] == "help_contact_pending" || params[:action] == "help_contact_resolved" %>
    <% if @sub_links_help %>
      <% @sub_links_help.each do |sublink| %>
        <div class="col-6 sub-link <%= sublink[:path].include?(request.fullpath) ? 'sub-link-active' : '' %>" >
          <%= link_to sublink[:path] do %>
            <%= sublink[:title].upcase %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <% if @sub_links_reviews %>
      <% @sub_links_reviews.each do |sublink| %>
        <div class="col-6 sub-link <%= sublink[:path].include?(request.fullpath) ? 'sub-link-active' : '' %>" >
          <%= link_to sublink[:path] do %>
            <%= sublink[:title].upcase %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/admin/help_contact_pending.html.erb
<%= render 'sub_links' %>

<div class="container" style="margin-top: 8rem !important;">

  <span class="section-subtitle mb-3">Consultas Pendientes</span>

  <div class="cards mb-4 mt-3">
    <div class="row">
      <% if @consultas != [] %>
        <% @consultas.each_with_index do |consulta, index| %>
          <div id="accordion">
            <div id="heading-<%= "#{index}" %>">
              <button class="w-100 help-card" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-<%= "#{index}" %>" aria-expanded="false" aria-controls="collapse-<%= "#{index}" %>">
                <div class="user d-flex justify-content-between py-3">
                  <div class="d-flex">
                    <%= image_tag('profile-icon.png') %>
                    <div class="d-flex flex-column justify-content-center" style="margin-left: 0.5rem;">
                      <span class="subtitle" style="text-align: start;">
                        <strong>
                          <%= consulta.user.nombre %>
                          <%= consulta.user.apellido %>
                        </strong>
                        realizó una nueva consulta.
                      </span>
                    </div>
                  </div>
                  <div class="d-flex align-items-center">
                    <small>Realizada el: <%= consulta.created_at.to_date.strftime("%d/%m/%Y") %></small>
                  </div>
                  <%= image_tag('arrow-down.svg') %>
                </div>
              </button>
            </div>

            <div id="collapse-<%= "#{index}" %>" class="collapse consultas-card" aria-labelledby="heading-<%= "#{index}" %>" data-bs-parent="#accordion">
              <div class="card-body mb-3 container py-0 px-3" style="margin-top: 10px !important;">

                <div class="detalles d-flex justify-content-between py-3" style="border-top: none;">
                  <div class="d-flex flex-column">
                    <span class= "subtitle"><strong>Email:</strong> <span class= "text"><%= consulta.user.email %> </span></span>
                    <span class= "subtitle"><strong>Telefono:</strong> <span class= "text"><%= consulta.user.phone %> </span></span>
                    <span class= "subtitle"><strong>Perfil:</strong> <span class= "text"><%= link_to 'Ver Perfil', profile_show_path(consulta.user.id) %> </span></span>
                          <%= simple_form_for @conversation, url: conversaciones_create_path, data: { turbo: false } do |f| %>
                            <%= hidden_field_tag(:sender_id, current_user.id) %>
                            <%= hidden_field_tag(:recipient_id, consulta.user.id) %>
                            <%= f.button :button, class: "btn-submit mt-2" do %>
                              <span>ENVIAR MENSAJE</span>
                            <% end %>
                          <% end %>
                  </div>
                </div>

                <div class="mt-3">
                  <%= button_to admin_help_update_path(consulta.id), method: :put, class: "btn btn-primary" do %>
                    Marcar como resuelto
                  <% end %>
                </div>

                <div class="pedigree d-flex flex-column py-3" style="border-bottom: none;">
                  <span class= "subtitle"><strong>Consulta:</strong></span>
                  <span class= "text"><%= consulta.message %> </span>
                </div>

              </div>
            </div>
          </div>

        <% end %>
      <% else %>
        <div class="d-flex flex-column justify-content-center align-items-center" style="height: 30vh;">
          <span>No hay consultas pendientes aun</span>
          <%= link_to home_path, class: "btn-submit mt-5 d-flex align-items-center justify-content-center" do %>
            <span>VOLVER AL INICIO</span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/help_contact_resolved.html.erb
<%= render 'sub_links' %>

<div class="container" style="margin-top: 8rem !important;">

  <span class="section-subtitle mb-3">Consultas Resueltas</span>

  <div class="cards mb-4 mt-3">
    <div class="row">
      <% if @consultas != [] %>
        <% @consultas.each_with_index do |consulta, index| %>
          <div id="accordion">

            <div id="heading-<%= "#{index}" %>">
              <button class="w-100 help-card" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-<%= "#{index}" %>" aria-expanded="false" aria-controls="collapse-<%= "#{index}" %>">
                <div class="user d-flex justify-content-between py-3">
                  <div class="d-flex">
                    <%= image_tag('profile-icon.png') %>
                    <div class="d-flex align-items-center justify-content-start" style="margin-left: 0.5rem;">
                      <span class="subtitle" style="text-align: start;">
                        Consulta realizada por
                        <strong>
                          <%= consulta.user.nombre %>
                          <%= consulta.user.apellido %>
                        </strong>
                      </span>
                    </div>
                  </div>
                  <div class="d-flex align-items-center">
                    <small>Realizada el: <%= consulta.created_at.to_date.strftime("%d/%m/%Y") %></small>
                  </div>
                  <%= image_tag('arrow-down.svg') %>
                </div>
              </button>
            </div>

            <div id="collapse-<%= "#{index}" %>" class="collapse consultas-card" aria-labelledby="heading-<%= "#{index}" %>" data-bs-parent="#accordion">
              <div class="card-body mb-3 container py-0 px-3" style="margin-top: 10px !important;">
                <div class="detalles d-flex justify-content-between py-3" style="border-top: none;">
                  <div class="d-flex flex-column">
                    <span class= "subtitle"><strong>Email:</strong> <span class= "text"><%= consulta.user.email %> </span></span>
                    <span class= "subtitle"><strong>Telefono:</strong> <span class= "text"><%= consulta.user.phone %> </span></span>
                    <span class= "subtitle"><strong>Perfil:</strong> <span class= "text"><%= link_to 'Ver Perfil', profile_show_path(consulta.user.id) %> </span></span>
                  </div>
                </div>

                <div class="mt-3">
                  <%= button_to admin_help_update_path(consulta.id), method: :put, class: "btn btn-primary" do %>
                    Marcar como no resuelto
                  <% end %>
                </div>

                <div class="pedigree d-flex flex-column py-3" style="border-bottom: none;">
                  <span class= "subtitle"><strong>Consulta:</strong></span>
                  <span class= "text"><%= consulta.message %> </span>
                </div>

              </div>
            </div>
          </div>

        <% end %>
      <% else %>
        <div class="d-flex flex-column justify-content-center align-items-center" style="height: 30vh;">
          <span>No hay consultas resueltas aun</span>
          <%= link_to home_path, class: "btn-submit mt-5 d-flex align-items-center justify-content-center" do %>
            <span>VOLVER AL INICIO</span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/reviews_pending.html.erb
<%= render 'sub_links' %>

<div class="container" style="margin-top: 8rem !important;">

  <span class="section-subtitle mb-3">Reseñas no aprobadas</span>

  <div class="cards mb-4 mt-3">
    <div class="row">
      <% if @reviews != [] %>
        <% @reviews.each_with_index do |review, index| %>
          <div id="accordion">
            <div id="heading-<%= "#{index}" %>">
              <button class="w-100 help-card" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-<%= "#{index}" %>" aria-expanded="false" aria-controls="collapse-<%= "#{index}" %>">
                <div class="user d-flex justify-content-between py-3">
                  <div class="d-flex">
                    <%= image_tag('profile-icon.png') %>
                    <div class="d-flex flex-column justify-content-center" style="margin-left: 0.5rem;">
                      <span class="subtitle" style="text-align: start;">
                        <strong>
                          <%= User.find(review.writer_id).nombre %>
                          <%= User.find(review.writer_id).apellido %>
                        </strong>
                        realizó una nueva review.
                      </span>
                    </div>
                  </div>
                  <div class="d-flex align-items-center">
                    <small>Realizada el: <%= review.created_at.to_date.strftime("%d/%m/%Y") %></small>
                  </div>
                  <%= image_tag('arrow-down.svg') %>
                </div>
              </button>
            </div>

            <div id="collapse-<%= "#{index}" %>" class="collapse consultas-card" aria-labelledby="heading-<%= "#{index}" %>" data-bs-parent="#accordion">
              <div class="card-body mb-3 container py-0 px-3" style="margin-top: 10px !important;">

                <div class="detalles d-flex justify-content-between py-3" style="border-top: none;">
                  <div class="d-flex flex-column">
                    <span class= "subtitle"><strong>Reseña para:</strong> <span class= "text"><%= review.user.nombre %> <%= review.user.apellido %></span></span>
                    <span class= "subtitle"><strong>Perfil:</strong> <span class= "text"><%= link_to 'Ver Perfil', profile_show_path(review.user) %> </span></span>
                  </div>
                </div>

                <div class="mt-3">
                  <%= link_to 'Marcar como aprobada', approve_review_path(review.id), class: "btn btn-primary" %>
                  <%= link_to 'Eliminar', review_destroy_path(review.id), class: "btn btn-primary", data: { turbo_method: :delete } %>
                </div>

                <div class="pedigree d-flex flex-column py-3" style="border-bottom: none;">
                  <div>
                    <span class= "subtitle"><strong>Rating:</strong></span>
                    <span class= "text">
                      <small >
                        <% review.rating.times do %>
                          <i class="fas fa-star review-star-icon"></i>
                        <% end %>
                        <%= review.rating %>/5
                      </small>
                    </span>
                  </div>
                  <div>
                    <span class= "subtitle"><strong>Comentario:</strong></span>
                    <span class= "text"><%= review.comment %> </span>
                  </div>
                </div>

              </div>
            </div>
          </div>

        <% end %>
      <% else %>
        <div class="d-flex flex-column justify-content-center align-items-center" style="height: 30vh;">
          <span>No hay reseñas pendientes aun</span>
          <%= link_to home_path, class: "btn-submit mt-5 d-flex align-items-center justify-content-center" do %>
            <span>VOLVER AL INICIO</span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/reviews_resolved.html.erb
<%= render 'sub_links' %>

<div class="container" style="margin-top: 8rem !important;">

  <span class="section-subtitle mb-3">Reseñas aprobadas</span>

  <div class="cards mb-4 mt-3">
    <div class="row">
      <% if @reviews != [] %>
        <% @reviews.each_with_index do |review, index| %>
          <div id="accordion">
            <div id="heading-<%= "#{index}" %>">
              <button class="w-100 help-card" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-<%= "#{index}" %>" aria-expanded="false" aria-controls="collapse-<%= "#{index}" %>">
                <div class="user d-flex justify-content-between py-3">
                  <div class="d-flex">
                    <%= image_tag('profile-icon.png') %>
                    <div class="d-flex flex-column justify-content-center" style="margin-left: 0.5rem;">
                      <span class="subtitle" style="text-align: start;">
                        <strong>
                          <%= User.find(review.writer_id).nombre %>
                          <%= User.find(review.writer_id).apellido %>
                        </strong>
                        realizó una nueva review.
                      </span>
                    </div>
                  </div>
                  <div class="d-flex align-items-center">
                    <small>Realizada el: <%= review.created_at.to_date.strftime("%d/%m/%Y") %></small>
                  </div>
                  <%= image_tag('arrow-down.svg') %>
                </div>
              </button>
            </div>

            <div id="collapse-<%= "#{index}" %>" class="collapse consultas-card" aria-labelledby="heading-<%= "#{index}" %>" data-bs-parent="#accordion">
              <div class="card-body mb-3 container py-0 px-3" style="margin-top: 10px !important;">

                <div class="detalles d-flex justify-content-between py-3" style="border-top: none;">
                  <div class="d-flex flex-column">
                    <span class= "subtitle"><strong>Reseña para:</strong> <span class= "text"><%= review.user.nombre %> <%= review.user.apellido %></span></span>
                    <span class= "subtitle"><strong>Perfil:</strong> <span class= "text"><%= link_to 'Ver Perfil', profile_show_path(review.user) %> </span></span>
                  </div>
                </div>

                <div class="mt-3">
                  <%= link_to 'Marcar como no aprobada', disapprove_review_path(review.id), class: "btn btn-primary" %>
                  <%= link_to 'Eliminar', review_destroy_path(review.id), class: "btn btn-primary", data: { turbo_method: :delete } %>
                </div>

                <div class="pedigree d-flex flex-column py-3" style="border-bottom: none;">
                  <div>
                    <span class= "subtitle"><strong>Rating:</strong></span>
                    <span class= "text">
                      <small >
                        <% review.rating.times do %>
                          <i class="fas fa-star review-star-icon"></i>
                        <% end %>
                        <%= review.rating %>/5
                      </small>
                    </span>
                  </div>
                  <div>
                    <span class= "subtitle"><strong>Comentario:</strong></span>
                    <span class= "text"><%= review.comment %> </span>
                  </div>
                </div>

              </div>

              </div>
            </div>
          </div>

        <% end %>
      <% else %>
        <div class="d-flex flex-column justify-content-center align-items-center" style="height: 30vh;">
          <span>No hay reseñas aprobadas aun</span>
          <%= link_to home_path, class: "btn-submit mt-5 d-flex align-items-center justify-content-center" do %>
            <span>VOLVER AL INICIO</span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>