config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :registrations => 'registrations',
    ## :sessions => 'users/sessions'
  }

  root to: "pages#onboarding", as: 'onboarding'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  mount ActionCable.server => '/cable'

  # Home routes
  get 'home', to: 'pages#home', as: 'home'
  get 'slide1', to: 'pages#slide1', as: 'slide1'
  get 'slide2', to: 'pages#slide2', as: 'slide2'
  get 'slide3', to: 'pages#slide3', as: 'slide3'

  # Horses routes
  get 'horses/:id/edit', to: 'horses#edit', as: "horse_edit"
  get 'horses', to: 'horses#index'
  get 'potros', to: 'horses#potros', as: 'potros'
  get 'horses/filtros', to: 'horses#filtros', as: :horses_filtros
  post 'horses/aplicar_filtros', to: 'horses#aplicarfiltros', as: :horses_aplicar_filtros
  get 'horses/resultados', to: 'horses#resultados', as: :horses_results
  get 'horses/new', to: 'horses#new', as: 'horse_new'
  get 'horses/:id', to: 'horses#show', as: "horse_show"
  post 'horses', to: 'horses#create'
  put 'horses/:id', to: 'horses#update', as: "horse_update"
  delete 'horses/:id', to: 'horses#destroy', as: :horses_destroy
  delete 'horses/:id/delete_video', to: 'horses#delete_video', as: :delete_video_horse

  # Auctions routes
  get 'active_auctions', to: 'auctions#active_auctions', as: 'active_auctions'
  get 'next_acutions', to: 'auctions#next_auctions', as: 'next_auctions'
  get 'auctions/new', to: 'auctions#new'
  post 'auctions', to: 'auctions#create'
  get 'auctions/:id', to: 'auctions#show', as: 'auction'
  get 'auctions/:id/edit', to: 'auctions#edit'
  put 'auctions/:id', to: 'auctions#update'
  delete 'auctions/:id', to: 'auctions#destroy', as: :auction_destroy

  # Lotes views
  get 'auctions/:id/lotes', to: 'lotes#index'
  get 'auctions/:id/lotes/:id', to: 'lotes#show'
  get 'auctions/:id/lotes/new', to: 'lotes#new'
  post 'auctions/:id/lotes', to: 'lotes#create'
  get 'auctions/:id/lotes/:id/edit', to: 'lotes#edit'
  put 'auctions/:id/lotes/:id', to: 'lotes#update'

  # Menu views
  get 'search', to: 'pages#search', as: 'search'
  get 'add', to: 'pages#add', as: 'add'

  # Profile views
  get 'perfiles', to: 'profiles#profile_index', as: 'profile_index'
  get 'perfiles/:id', to: 'profiles#show', as: 'profile_show'
  resources :users do
    resources :reviews, only: :create
    end
  get 'favoritos/caballos', to: 'profiles#favorite_caballos', as: 'profile_favorite_caballos'
  get 'favoritos/remates', to: 'profiles#favorite_remates', as: 'profile_favorite_remates'
  get 'notificationes', to: 'profiles#notification', as: 'profile_notification'
  get 'mis_publicaciones/caballos', to: 'profiles#publication_caballos', as: 'profile_publication_caballos'
  get 'mis_publicaciones/remates', to: 'profiles#publication_remates', as: 'profile_publication_remates'
  post 'favorite_horse/:horse', to: 'favorites#update_horse', as: 'favorite_horse'
  post 'favorite_auction/:auction', to: 'favorites#update_auction', as: 'favorite_auction'
  get 'gracias_registo', to: 'pages#gracias', as: 'registro_gracias'

  # Reviews routes
  get 'approve_review/:id', to: 'reviews#approve', as: 'approve_review'
  get 'disapprove_review/:id', to: 'reviews#disapprove', as: 'disapprove_review'
  delete 'reviews/:id', to: 'reviews#destroy', as: 'review_destroy'

  # Conversation routes
  get 'conversaciones/activas', to: 'conversations#conversaciones_activas', as: 'conversaciones_activas'
  get 'conversaciones/archivadas', to: 'conversations#conversaciones_archivadas', as: 'conversaciones_archivadas'
  post 'conversaciones', to: 'conversations#create', as: 'conversaciones_create'
  get 'conversaciones/:id', to: 'conversations#show', as: 'conversacion_show'
  put 'conversaciones/:id/archivar', to: 'conversations#archivar', as: 'conversacion_archivar'
  put 'conversaciones/:id/desarchivar', to: 'conversations#desarchivar', as: 'conversacion_desarchivar'
  delete 'conversaciones/:id', to: 'conversations#destroy', as: 'conversacion_destroy'

  # Messages routes
  post 'mensajes', to: 'messages#create', as: 'conversation_messages'
  get 'favorite_horse/:id', to: 'favorites#delete_horse', as: 'favorite_delete_horse'
  get 'favorite_auction/:id', to: 'favorites#delete_auction', as: 'favorite_delete_auction'

  # Contact routes
  get '/contact', to: 'contact#index'
  post '/send_message', to: 'contact#send_message'

  # Admin routes
  get 'admin/contact/pending', to: 'admin#help_contact_pending', as: 'admin_help_contact_pending'
  get 'admin/contact/resolved', to: 'admin#help_contact_resolved', as: 'admin_help_contact_resolved'
  put 'admin/contact/:id', to: 'admin#help_update', as: 'admin_help_update'
  get 'admin/reviews/pending', to: 'admin#reviews_pending', as: 'admin_reviews_pending'
  get 'admin/reviews/resolved', to: 'admin#reviews_resolved', as: 'admin_reviews_resolved'
  
  # Pub routes
  get 'pubs', to: 'pubs#index'
  post 'pubs', to: 'pubs#create'
  post 'pubs/delete_pub_img', to: 'pubs#delete_pub_img', as: 'delete_pub_img'
  post 'pubs/delete_pub_video', to: 'pubs#delete_pub_video', as: 'delete_pub_video'

end

app/controllers/horses_controller.rb
require 'net/http'
require 'net/http/post/multipart'
require 'cloudinary'
require 'browser'

class HorsesController < ApplicationController

  ALLOWED_VIDEO_FORMATS = %w(
    video/quicktime video/mpeg video/avi video/x-flv video/x-f4v
    video/mp4 video/x-m4v video/x-ms-asf video/x-ms-wmv video/x-ms-wmx
    video/x-ms-wvx video/vob video/mod video/3gpp video/3gpp2
    video/x-matroska video/divx video/xvid video/webm
  )

  before_action :set_horse, only: %i[show edit update destroy]
  
  def initialize
    super
    numbers = []
    (0..220).each do |num|
      major = num / 100
      minor = num % 100
      if major >= 1 && major <= 2 && minor > 0
        numbers << "#{major}.#{format('%02d', minor)}"
      end
    end
    @alzada = numbers
    @height = ["0.50", "0.60", "0.70", "0.80", "0.90", "1.00", "1.10", "1.20", "1.30", "1.40", "1.50", "1.60", "1.70", "1.80", "1.90", "2.00"]
  end

  def index
    @horses = Horse.all.where.not(user_id: current_user.id)
    @section_title = "Caballos"
    @filtros = 'true'
  end

  def potros
    @horses_user = Horse.all.where.not(user_id: current_user.id)
    @horses = @horses_user.select do |horse|
      horse.age <= 4
    end
    @section_title = "Potros"
    @filtros = 'true'
  end

  def show
    @section_title = @horse.name
    @horse = Horse.find(params[:id])
    @horses = Horse.all.where(user_id: @horse.user.id).where.not(id: params[:id].to_i)
    @share_like = 'true'
    @conversation = Conversation.new
    @favorite_exists = Favorite.where(horse: @horse, user: current_user) != []
    if @horse.video != nil
      url = @horse.video
      url_path = url.sub("http://", "//")
      @horse.video = url_path
    end
    
    @pub_video = Pub.all.where(asset_type: "video")[0]
    puts '=============='
    puts browser.safari?(">17")
    puts '=============='
  end

  def new
    @horse = Horse.new
    @section_title = "Añadir caballo"
  end

  def create
    @horse = Horse.create(horse_params)
    @horse.user = current_user
    
    if params[:horse][:photos].present?
      @horse.photos.attach(params[:horse][:photos])
    end

    if params[:horse][:food_photo].present?
      @horse.food_photo.attach(params[:horse][:food_photo])
    end
    
    puts @horse.inspect
    
    if params[:horse][:video] != nil
      
      if ALLOWED_VIDEO_FORMATS.include?(params[:horse][:video].content_type)
        puts "--------------------------------"
        puts "Inicio post check de url"
        
        success, url = post_video_to_cloudinary(params[:horse][:video], params[:horse][:name])
        
        if success
          
          puts "--------------------------------"
          puts "Inicio post to cloudinary"
          @horse.video = url

          if @horse.save
          
            @notification = Notification.new(
              user_id: current_user.id,
              description: "Publicación creada con éxito.",
              tipo: "publication",
              horse_id: @horse.id
            )

            if @notification.save
            
              redirect_to profile_publication_caballos_path, notice: "Caballo creado con éxito"
            
            else
            
              @section_title = "Añadir caballo"
              flash[:alert] = "No se pudo crear el caballo, intente nuevamente"
              render :new, status: :unprocessable_entity

            end
          
          else

            @section_title = "Añadir caballo"
            flash[:alert] = "No se pudo crear el caballo, intente nuevamente"
            render :new, status: :unprocessable_entity

          end

        else

          flash[:alert] = url
          render :new, status: :unprocessable_entity
          
        end
      else
        @section_title = "Añadir caballo"
        flash[:alert] = "Por favor cargue un video con formato válido"
        render :new, status: :unprocessable_entity
      end

    else
      if @horse.save
        @notification = Notification.new(
          user_id: current_user.id,
          description: "Publicación creada con éxito.",
          tipo: "publication",
          horse_id: @horse.id
        )
        redirect_to profile_publication_caballos_path, notice: "Caballo creado con éxito"
      else
        @section_title = "Añadir caballo"
        flash[:alert] = "No se pudo crear el caballo, intente nuevamente"
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit
    @section_title = "Editar caballo"
    @horse = Horse.find(params[:id])
  end

  def update
    if params[:horse][:photos].present?
      @horse.photos.attach(params[:horse][:photos])
    end

    if params[:horse][:food_photo].present?
      @horse.food_photo.attach(params[:horse][:food_photo])
    end    

    # If the video is uploaded
    if horse_params[:video] != nil
      if ALLOWED_VIDEO_FORMATS.include?(params[:horse][:video].content_type)
        puts "--------------------------------"
        puts "Inicio post check de url"
        video_public_id = make_video_public_id(@horse[:name])
    
        success = Cloudinary::Uploader.destroy(video_public_id, resource_type: 'video')
        
        if success['result'] == 'ok'
          puts 'EL VIDEO SE ELIMINO EXITOSAMENTE'
        else
          puts 'NO SE PUDO ELIMINAR EL VIDEO'
        end

        url = post_video_to_cloudinary(params[:horse][:video], @horse[:name])
        
        if url == "Excedio el limite de videos"
          puts "--------------------ERRROR----------------"
          puts "Excedio el limite de videos"
          @section_title = "Editar caballo"
          @horse = Horse.find(params[:id])
          flash.now[:alert] = "No se pudo editar el caballo, el almacenamiento de videos esta lleno"
          render :edit, status: :unprocessable_entity
        else
          @horse.video = url
          if @horse.save
            if @horse.update(horse_params.reject { |key, _| key == "video" || key == "photos" })
              redirect_to horse_show_path(@horse), notice: "Caballo editado con éxito"
            else
              @section_title = "Editar caballo"
              @horse = Horse.find(params[:id])
              flash.now[:alert] = "No se pudo editar el caballo, intente nuevamente"
              render :edit, status: :unprocessable_entity
            end
          else
            @section_title = "Editar caballo"
            @horse = Horse.find(params[:id])
            flash.now[:alert] = "No se pudo editar el caballo, intente nuevamente"
            render :edit, status: :unprocessable_entity
          end
        end
      else
        @section_title = "Editar caballo"
        @horse = Horse.find(params[:id])
        render :edit, status: :unprocessable_entity, alert: "Por favor cargue un video con formato válido"
      end
    else
      # If no video is uploaded
      if @horse.update(horse_params.reject { |key, _| key == "video" || key == "photos" })
        redirect_to horse_show_path(@horse)
      else
        @section_title = "Editar caballo"
        @horse = Horse.find(params[:id])
        render :edit, status: :unprocessable_entity, alert: "No se pudo editar el caballo, intente nuevamente"
      end
    end
  end

  def filtros
    @filtro = Filtro.new
    @horses = Horse.all.where.not(user_id: current_user.id)
    @jinetes = @horses.map { |horse| horse.rider }.uniq
    @paises = @horses.map { |horse| horse.country }.uniq
    @section_title = "Caballos - Filtros"
  end

  def aplicarfiltros
    jinete = params[:filtro][:jinete]
    edad = params[:filtro][:edad]
    altura = params[:filtro][:altura]
    pais = params[:filtro][:pais]
    redirect_to horses_results_path(filtro: "OK", jinete: jinete, edad: edad, altura: altura, pais: pais)
  end

  def resultados
    @section_title = "Resultados"
    @filtros = 'true'
    # Resultados
    if params[:filtro] == "OK"
      @horses_all = Horse.all.where.not(user_id: current_user.id)
      @horses = Horse.all.where.not(user_id: current_user.id)
      # Filtro por jinete
      if params[:jinete] != ""
        @horses = @horses_all.where(rider: params[:jinete])
      end
      # Filtro por Edad
      if params[:edad] != "0"
        if @horses
          @horses = @horses.where(age: params[:edad])
        else
          @horses = @horses_all.where(age: params[:edad])
        end
      end
      # Filtro por Altura
      if params[:altura] != ""
        if @horses
          @horses = @horses.where(height: params[:altura].to_s)
        else
          @horses = @horses_all.where(height: params[:altura].to_s)
        end
      end
      # Filtro por Ubicacion
      if params[:pais] != ""
        if @horses
          @horses = @horses.where(country: params[:pais])
        else
          @horses = @horses_all.where(country: params[:pais])
        end
      end
    end
  end

  def destroy
    @horse = Horse.find(params[:id])
    
    video_public_id = make_video_public_id(@horse[:name])
    
    success = Cloudinary::Uploader.destroy(video_public_id, resource_type: 'video')

    puts success

    if @horse.destroy
      redirect_to profile_publication_caballos_path, notice: "Se elimino correctamente la publicacion"
    else
      render 'mis_publicaciones/caballos', alert: "No se pudo eliminar la publicacion, intente nuevamente"
    end
  end

  def post_video_to_wistia(name = "", path_to_video)
    uri = URI('https://upload.wistia.com/')
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    # Construct the request.
    request = Net::HTTP::Post::Multipart.new uri.request_uri, {
      # 'access_token' => "596f97ec721a7997a641b5bd4c64f4e1f838d99e34d2dca91c8ccd46d1c18c8a",
      'access_token' => "f1e7de6e254c1d532ba7586cafc33e27267c9cafb8b134834b7870c08d6c93b7",
      'file' => UploadIO.new(
                  File.open(path_to_video),
                  'application/octet-stream',
                  File.basename(path_to_video)
                )
    }
    # Make it so!

app/views/horses/show.html.erb
<!-- Content -->
<div class="horses-show d-flex flex-column align-items-center" data-controller='share'>
  <div class="col-lg-6 col-sm-10 col-md-8 col-12 px-0" style="box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">

    <!---------- Carousel ------->
    <div class="foto w-100 h-100 mb-3 d-flex justify-content-center">
      <div id="carouselExampleIndicators" class="carousel slide w-100" data-interval="false">
        <ol class="carousel-indicators" style="z-index: 3 !important;">
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">
          <% if @horse&.photos&.attached? %>
            <div class="carousel-item active d-flex align-items-center justify-content-center carousel-photo-div"  style="height: 400px !important">
              <%= cl_image_tag @horse&.photos&.first&.key, class: "carousel-photo", style: "height: 18.75rem;" %>
            </div>
          <% else %>
            <div class="carousel-item active" style="height: 400px !important">
              <%= image_tag('caballo-placeholder-solo.png', class: "w-100", style: "height: 25rem;") %>
            </div>
          <% end %>
          
          <% if @horse.video %>

            <div class="carousel-item" style="height: 400px !important">
              <% if !browser.safari?("<17") %>
                <input type="hidden" id="video_url" value="<%= @horse.video %>" />
                <video width="100%" height="100%" id="main_video" src="<%= @horse.video %>" type="video/mp4" controls muted playsinline style="background: white;"></video>
              <% else %>
                <iframe id="theiframe" src=<%= @horse.video %> allowtransparency="true" frameborder="0" scrolling="no" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="100%" height="400" onload="iframeclick()"></iframe>
              <% end %>
              <% if !@pub_video.nil? %>
                <%= video_tag(@pub_video["url"], id: "pub_video", controls: true, width: "100%", height: "100%", style: "display:none; background: white;", playsinline: true, muted: true) %>
              <% end %>
            </div>
            
          <% end %>
          
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

    <!---------- Favorite ------->
    <%= button_to favorite_horse_text(@horse), favorite_horse_path(horse: @horse), class: "horse_heart d-none", remote: true %>

    <div class="container px-3" style="margin-top: 1rem !important;">
      <div class="info">

        <div class="horse-titulo d-flex flex-column mb-4">
          <div class="d-flex">
            <span class="titulo mb-2 d-flex mr-2"><%= @horse.name %></span>
            <% if @horse.age <= 4 %>
            <div class="pt-1">
              <div class="potro d-flex align-items-center justify-content-center">
                <%= image_tag 'potro-icon.svg' %>
                <span class="ml-1 potro-span">potro</span>
              </div>
            </div>
            <% end %>
            <% if @horse.user == current_user || current_user.admin %>
              <div class="ml-4 pt-1 d-flex align-items-start">
                <%= link_to horse_edit_path(@horse) do %>
                  <i class="fa-solid fa-pen-to-square mr-2" style="color: black; font-size: 24px;"></i>
                <% end %>
                <%= button_to horses_destroy_path(@horse), method: :delete, class: "btn d-inline-flex p-0", id: "delete-horse"  do %>
                  <i class="fa-solid fa-trash" style="color: black; font-size: 20px;"></i>
                <% end %>
              </div>
            <% end %>
          </div>
          <span class= "text"><%= @horse.description %></span>
        </div>

        <div class="detalles d-flex flex-column py-3">
          <% if @horse.height.present? %>
            <span class="subtitle">Altura: <span class= "text"><%= @horse.height %>m</span></span>
          <% end %>
          <span class="subtitle">Edad: <span class= "text"><%= @horse.age %> años</span></span>
          <span class="subtitle">Fecha de Nacimiento: <span class= "text"><%= @horse.birthday %></span></span>
          <span class="subtitle">Sexo: <span class= "text"><%= @horse.gender %></span></span>
          <% if @horse.country.present? %>
            <span class="subtitle">País: <span class= "text"><%= @horse.country %></span></span>
          <% end %>
          <% if @horse.alzada.present? %>
            <span class="subtitle">Alzada: <span class= "text"><%= @horse.alzada %></span></span>
          <% end %>
          <% if @horse.rider.present? %>
            <span class="subtitle">Jinete: <span class= "text"><%= @horse.rider %></span></span>
          <% end %>
        </div>

        <div class="pedigree d-flex flex-column py-3">
          <span class="subtitle">Pedigree</span>
          <% if @horse.pedigree.present? %>
            <%= link_to 'Ver pedigree', @horse.pedigree %>
          <% end %>

          <% if @horse.food_photo.present? %>  
            <%= link_to 'Ver imagen', @horse.food_photo %>
          <% end %>

          <% if @horse.pedigree.blank? && @horse.food_photo.blank? %>
            <span class="text">No posee pedigree</span>
          <% end %>

        </div>

        <div class="user d-flex py-3">
          <div>
            <%= image_tag('profile-icon.png') %>
          </div>
          <div class="d-flex flex-column justify-content-center" style="margin-left: 1rem;">
            <span class="subtitle"><%= @horse.user.nombre %> <%= @horse.user.apellido %></span>
            <span class="sub-subtitle"><%= @horse.user.establishment %></span>
            <% if @horse.user.id != current_user.id %>
              <%= link_to profile_show_path(@horse.user.id) do %>
                <span class="link">Ver perfil</span>
              <% end %>
            <% end %>
          </div>
        </div>

        <% if @horse.user.id != current_user.id %>
          <div class="msg d-flex py-3">
            <div class="d-flex w-100 justify-content-around">
              <div class="col consultar mt-2">
                <%= simple_form_for @conversation, url: conversaciones_create_path(horse_id: @horse.id), data: { turbo: false } do |f| %>
                  <%= hidden_field_tag(:sender_id, current_user.id) %>
                  <%= hidden_field_tag(:recipient_id, @horse.user_id) %>
                  <%= f.button :button do %>
                    <%= image_tag('message-filled.png') %>
                    <span>CONSULTAR</span>
                  <% end %>
                <% end %>
              </div>
              <div class="col consultar">
                <button>
                  <a href="https://api.whatsapp.com/send?phone=<%= @horse.user.country_code %><%= @horse.user.phone %>">
                  <span><i class="fab fa-whatsapp"></i></span>
                  <span>Whatsapp</span>
                  </a>
                </button>
              </div>
            </div>
          </div>
        <% end %>

      </div>

      <div class="publicaciones mt-3">
        <span class="subtitle">Publicaciones relacionadas</span>
        <div class="container justify-content-center">
          <% if @horses != [] %>
            <% @horses.each do |horse| %>
                <%= render 'shared/horse_card', horse: horse %>
            <% end %>
          <% else %>
            <div class="d-flex justify-content-center align-items-center" style="height: 30vh;">
              <span>No hay recomendaciones disponibles todavia</span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  buttons = document.querySelectorAll('.horse_heart')
    buttons.forEach(
    function(button) {
      if (button.innerText == "fav"){
        button.innerHTML = "<i class='fa-solid fa-heart'></i>"
      } else if (button.innerText == "nofav"){
        button.innerHTML = "<i class='fa-regular fa-heart'></i>"
      }
      button.addEventListener('click', function() {
        if (button.innerHTML == `<i class="fa-solid fa-heart"></i>`) {
          button.innerHTML = `<i class="fa-regular fa-heart"></i>`
        } else if (button.innerHTML == `<i class="fa-regular fa-heart"></i>`){
          button.innerHTML = `<i class="fa-solid fa-heart"></i>`
        }
      })
    }
  )

  // function iframeclick() {
  //   document.getElementById("theiframe").contentWindow.document.body.onclick = function() {
  //     // document.getElementById("theiframe").contentWindow.location.reload();
  //     console.log('clickeaste');
  //   }
  // }
  
</script>

<script>
  buttons = document.querySelectorAll('.horse_heart_index')
    buttons.forEach(
    function(button) {
      if (button.innerText == "fav"){
        button.innerHTML = "<i class='fa-solid fa-heart'></i>"
      } else if (button.innerText == "nofav"){
        button.innerHTML = "<i class='fa-regular fa-heart'></i>"
      }
      button.addEventListener('click', function() {
        if (button.innerHTML == `<i class="fa-solid fa-heart"></i>`) {
          button.innerHTML = `<i class="fa-regular fa-heart"></i>`
        } else if (button.innerHTML == `<i class="fa-regular fa-heart"></i>`){
          button.innerHTML = `<i class="fa-solid fa-heart"></i>`
        }
      })
    }
  )

  const deleteButton = document.getElementById('delete-horse');
  deleteButton.addEventListener('click', function(event) {
    event.preventDefault();
    const confirmDelete = confirm('¿Estás seguro de eliminar el caballo?');
    if (confirmDelete) {
      const form = event.currentTarget.closest('form');
      form.submit();
    }
  });
</script>

<script>

  document.addEventListener("DOMContentLoaded", init, false);
  
  var main_video = document.getElementById("main_video");
  var pub_video = document.getElementById("pub_video");
  // var video_url = document.getElementById("video_url");
  // pub_video.style.display = "none";

  function init() {
    // assign src to video tag
    // main_video.setAttribute('src', video_url.value);
    // main_video.load();
    if (pub_video != null){
      main_video.addEventListener("click", play_clicked, false);
    }
  }

  function play_clicked() {
    
    if (main_video.currentTime == 0){
      main_video.style.display = "none";
      pub_video.style.display = "block";
      pub_video.play();
      pub_video.muted = false;
    }
  
  }

  pub_video.onended = function() {
    main_video.currentTime = 0;
    main_video.muted = false;
    pub_video.style.display = "none";
    main_video.style.display = "block";
    main_video.play();  
  }

  

</script>

<style>
  .horse_heart{
    border: none;
    background: none;
    padding: 0;
    color:white;
    font-size: 1.3rem;
  }

  .horse_heart_index{
    border: none;
    background: none;
    padding: 0;
    padding-top: 2px;
    color: #F2DA84;
    font-size: 1.3rem;
  }

  .horse_heart_home{
    border: none;
    background: none;
    padding: 0;
    padding-top: 2px;
    color: #F2DA84;
    font-size: 1.3rem;
  }

  a {
    color: white;
  }
</style>