config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :registrations => 'registrations',
    ## :sessions => 'users/sessions'
  }

  root to: "pages#onboarding", as: 'onboarding'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  mount ActionCable.server => '/cable'

  # Home routes
  get 'home', to: 'pages#home', as: 'home'
  get 'slide1', to: 'pages#slide1', as: 'slide1'
  get 'slide2', to: 'pages#slide2', as: 'slide2'
  get 'slide3', to: 'pages#slide3', as: 'slide3'

  # Horses routes
  get 'horses/:id/edit', to: 'horses#edit', as: "horse_edit"
  get 'horses', to: 'horses#index'
  get 'potros', to: 'horses#potros', as: 'potros'
  get 'horses/filtros', to: 'horses#filtros', as: :horses_filtros
  post 'horses/aplicar_filtros', to: 'horses#aplicarfiltros', as: :horses_aplicar_filtros
  get 'horses/resultados', to: 'horses#resultados', as: :horses_results
  get 'horses/new', to: 'horses#new', as: 'horse_new'
  get 'horses/:id', to: 'horses#show', as: "horse_show"
  post 'horses', to: 'horses#create'
  put 'horses/:id', to: 'horses#update', as: "horse_update"
  delete 'horses/:id', to: 'horses#destroy', as: :horses_destroy
  delete 'horses/:id/delete_video', to: 'horses#delete_video', as: :delete_video_horse

  # Auctions routes
  get 'active_auctions', to: 'auctions#active_auctions', as: 'active_auctions'
  get 'next_acutions', to: 'auctions#next_auctions', as: 'next_auctions'
  get 'auctions/new', to: 'auctions#new'
  post 'auctions', to: 'auctions#create'
  get 'auctions/:id', to: 'auctions#show', as: 'auction'
  get 'auctions/:id/edit', to: 'auctions#edit'
  put 'auctions/:id', to: 'auctions#update'
  delete 'auctions/:id', to: 'auctions#destroy', as: :auction_destroy

  # Lotes views
  get 'auctions/:id/lotes', to: 'lotes#index'
  get 'auctions/:id/lotes/:id', to: 'lotes#show'
  get 'auctions/:id/lotes/new', to: 'lotes#new'
  post 'auctions/:id/lotes', to: 'lotes#create'
  get 'auctions/:id/lotes/:id/edit', to: 'lotes#edit'
  put 'auctions/:id/lotes/:id', to: 'lotes#update'

  # Menu views
  get 'search', to: 'pages#search', as: 'search'
  get 'add', to: 'pages#add', as: 'add'

  # Profile views
  get 'perfiles', to: 'profiles#profile_index', as: 'profile_index'
  get 'perfiles/:id', to: 'profiles#show', as: 'profile_show'
  resources :users do
    resources :reviews, only: :create
    end
  get 'favoritos/caballos', to: 'profiles#favorite_caballos', as: 'profile_favorite_caballos'
  get 'favoritos/remates', to: 'profiles#favorite_remates', as: 'profile_favorite_remates'
  get 'notificationes', to: 'profiles#notification', as: 'profile_notification'
  get 'mis_publicaciones/caballos', to: 'profiles#publication_caballos', as: 'profile_publication_caballos'
  get 'mis_publicaciones/remates', to: 'profiles#publication_remates', as: 'profile_publication_remates'
  post 'favorite_horse/:horse', to: 'favorites#update_horse', as: 'favorite_horse'
  post 'favorite_auction/:auction', to: 'favorites#update_auction', as: 'favorite_auction'
  get 'gracias_registo', to: 'pages#gracias', as: 'registro_gracias'

  # Reviews routes
  get 'approve_review/:id', to: 'reviews#approve', as: 'approve_review'
  get 'disapprove_review/:id', to: 'reviews#disapprove', as: 'disapprove_review'
  delete 'reviews/:id', to: 'reviews#destroy', as: 'review_destroy'

  # Conversation routes
  get 'conversaciones/activas', to: 'conversations#conversaciones_activas', as: 'conversaciones_activas'
  get 'conversaciones/archivadas', to: 'conversations#conversaciones_archivadas', as: 'conversaciones_archivadas'
  post 'conversaciones', to: 'conversations#create', as: 'conversaciones_create'
  get 'conversaciones/:id', to: 'conversations#show', as: 'conversacion_show'
  put 'conversaciones/:id/archivar', to: 'conversations#archivar', as: 'conversacion_archivar'
  put 'conversaciones/:id/desarchivar', to: 'conversations#desarchivar', as: 'conversacion_desarchivar'
  delete 'conversaciones/:id', to: 'conversations#destroy', as: 'conversacion_destroy'

  # Messages routes
  post 'mensajes', to: 'messages#create', as: 'conversation_messages'
  get 'favorite_horse/:id', to: 'favorites#delete_horse', as: 'favorite_delete_horse'
  get 'favorite_auction/:id', to: 'favorites#delete_auction', as: 'favorite_delete_auction'

  # Contact routes
  get '/contact', to: 'contact#index'
  post '/send_message', to: 'contact#send_message'

  # Admin routes
  get 'admin/contact/pending', to: 'admin#help_contact_pending', as: 'admin_help_contact_pending'
  get 'admin/contact/resolved', to: 'admin#help_contact_resolved', as: 'admin_help_contact_resolved'
  put 'admin/contact/:id', to: 'admin#help_update', as: 'admin_help_update'
  get 'admin/reviews/pending', to: 'admin#reviews_pending', as: 'admin_reviews_pending'
  get 'admin/reviews/resolved', to: 'admin#reviews_resolved', as: 'admin_reviews_resolved'
  
  # Pub routes
  get 'pubs', to: 'pubs#index'
  post 'pubs', to: 'pubs#create'
  post 'pubs/delete_pub_img', to: 'pubs#delete_pub_img', as: 'delete_pub_img'
  post 'pubs/delete_pub_video', to: 'pubs#delete_pub_video', as: 'delete_pub_video'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div data-controller="alert" class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div data-controller="alert" class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="d-flex w-100 justify-content-around">
    <div class="d-flex align-items-center flex-column justify-content-center text-center footer-box  <%= request.path.include?("/home") ? "active" : ""%>">
      <%= link_to home_path do %>
        <%= image_tag('home.png') %>
        <p class="description">Inicio</p>
      <% end %>
    </div>
    <div class="d-flex align-items-center flex-column justify-content-center text-center footer-box <%= request.path.include?("/search") ? "active" : ""%>">
      <%= link_to search_path do %>
        <%= image_tag('search.png') %>
        <p class="description">Buscar</p>
      <% end %>
    </div>
    <div class="d-flex align-items-center flex-column justify-content-center text-center footer-box <%= request.path.include?("/add") ? "active" : ""%>">
      <%= link_to add_path do %>
        <%= image_tag('agregar.png') %>
        <p class="description">Añadir</p>
      <% end %>
    </div>
    <div class="msg-container d-flex align-items-center flex-column justify-content-center text-center footer-box <%= request.path.include?("/conversaciones/") ? "active" : ""%>">
      <% if current_user && @total_msgs > 0 %>
        <div class='indicator'>
          <div class='noti-count'><%= @total_msgs%></div>
        </div>
      <% end %>
      <%= link_to conversaciones_activas_path do %>
        <%= image_tag('mensajes.png') %>
        <p class="description">Mensajes</p>
      <% end %>
    </div>
    <div class="d-flex align-items-center flex-column justify-content-center text-center footer-box <%= request.path.include?("/perfiles") ? "active" : ""%>">
      <%= link_to profile_index_path do %>
        <%= image_tag('perfil.png') %>
        <p class="description">Mi Perfil</p>
      <% end %>
    </div>
    <div class="d-flex align-items-center flex-column justify-content-center text-center footer-box">
      <span><a href="https://api.whatsapp.com/send?phone=59894020261"><i class="fab fa-whatsapp"></i></a></span>
      <p class="description">Contactanos</p>
    </div>
  </div>

</div>

<style>

.dotted {
  border: #000000;
  border-style: dashed;
}

.fab {
  color: #ffffff;
}

.msg-container {
  position: relative;
}

.indicator {
  width: 20px;
  height: 20px;
  position: absolute;
  z-index: 1000;
  top: 0;
  right: 0;
  background-color: red;
  border: 3px solid rgb(32, 123, 110);
  border-radius: 50%;
  display: flex;
  justify-content: center;
  align-items: center;
}

.noti-count {
  color: white;
  font-weight: 300;
}

.icon a {
  color: white;
}

.wrapper {
  display: inline-flex;
  list-style: none;
}

.wrapper .icon {
  position: relative;
  background: #000000;
  border-radius: 50%;
  margin: 0px 10px;
  width: 50px;
  height: 50px;
  font-size: 18px;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  box-shadow: 0 10px 10px rgba(0, 0, 0, 0.1);
  cursor: pointer;
  transition: all 0.2s cubic-bezier(0.68, -0.55, 0.265, 1.55);
}

.wrapper .tooltip {
  position: absolute;
  top: 0;
  font-size: 14px;
  background: #ffffff;
  color: #ffffff;
  padding: 5px 8px;
  border-radius: 5px;
  box-shadow: 0 10px 10px rgba(0, 0, 0, 0.1);
  opacity: 0;
  pointer-events: none;
  transition: all 0.3s cubic-bezier(0.68, -0.55, 0.265, 1.55);
}

.wrapper .tooltip::before {
  position: absolute;
  content: "";
  height: 8px;
  width: 8px;
  background: #ffffff;
  bottom: -3px;
  left: 50%;
  transform: translate(-50%) rotate(45deg);
  transition: all 0.3s cubic-bezier(0.68, -0.55, 0.265, 1.55);
}

.wrapper .icon:hover .tooltip {
  top: -45px;
  opacity: 1;
  visibility: visible;
  pointer-events: auto;
}

.wrapper .icon:hover span,
.wrapper .icon:hover .tooltip {
  text-shadow: 0px -1px 0px rgba(0, 0, 0, 0.1);
}

.whatsapp {
  --color: #198754;
}

.icon:hover,
.icon:hover .tooltip,
.icon:hover .tooltip::before {
  background: var(--color);
  color: white;
}

@media (max-width: 425px) {
  .description {
    font-size: 10px !important;
  }
}

@media (max-width: 375px) {
  .description {
    font-size: 9px !important;
  }
}

@media (max-width: 320px) {
  .description {
    font-size: 8px !important;
  }
}

</style>

app/views/shared/_horse_card.html.erb
<div class="card w-100 mb-3">  
  <div class="card-img-top ratio ratio-16x9">
    <% if horse&.photos&.first&.present? %>
      <%= cl_image_tag horse.photos.first.key, style: "object-fit: contain" %>
    <% else %>
      <%= image_tag 'caballo-placeholder-solo.png' %>
    <% end %>
  </div>
  <div class="card-content">
    <div class="nombre m-0 w-100"><span><%= horse.name %></span></div>
      <div class="p-2 d-flex">
        <div class="col-3 pl-0 d-flex align-items-center justify-content-center">
            <% if horse.age <= 4 %>
              <div class="potro d-flex align-items-center justify-content-center">
                  <%= image_tag 'potro-icon.svg' %>
                  <span class="ml-1 potro-span">potro</span>
              </div>
            <% end %>
        </div>
        <div class="col-6 d-flex justify-content-center link align-items-center">
            <%= link_to horse_show_path(horse.id) do %>
            <span>VER MAS</span>
            <% end %>
        </div>
        <div class="col-3 d-flex justify-content-end align-items-center pr-0">
            <div class="d-flex align-items-center justify-content-center">
            <%= button_to favorite_horse_text(horse), favorite_horse_path(horse: horse), class: "horse_heart_home mx-2", remote: true %>
            </div>
        </div>
      </div>
  </div>
</div>

<script>
  buttons = document.querySelectorAll('.horse_heart_home')
    buttons.forEach(
    function(button) {
      if (button.innerText == "fav"){
        button.innerHTML = "<i class='fa-solid fa-heart'></i>"
      } else if (button.innerText == "nofav"){
        button.innerHTML = "<i class='fa-regular fa-heart'></i>"
      }
      button.addEventListener('click', function() {
        if (button.innerHTML == `<i class="fa-solid fa-heart"></i>`) {
          button.innerHTML = `<i class="fa-regular fa-heart"></i>`
        } else if (button.innerHTML == `<i class="fa-regular fa-heart"></i>`){
          button.innerHTML = `<i class="fa-solid fa-heart"></i>`
        }
      })
    }
  )
</script>

<style>
  .horse_heart{
    border: none;
    background: none;
    padding: 0;
    color:white;
    font-size: 1.3rem;
  }

  .horse_heart_index{
    border: none;
    background: none;
    padding: 0;
    padding-top: 2px;
    color: #F2DA84;
    font-size: 1.3rem;
  }

  .horse_heart_home{
    border: none;
    background: none;
    padding: 0;
    padding-top: 2px;
    color: #F2DA84;
    font-size: 1.3rem;
  }
</style>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="d-flex align-items-center">

      <%# NAVBAR BRAND ICON %>
      <% if @navbar_brand %>
        <%= link_to home_path, class: "navbar-brand" do %>
          <%= image_tag 'follow-horse-logo-sin-texto.png' %>
        <% end %>

      <%# BACK FUNCTIONALITY ICON %>
      <% else %>
        <a href="javascript:history.back()"><%= image_tag('arrow_forward.png', style: 'margin-right: 1.25rem') %></a>
      <% end %>

      <%# SECTION TITLE %>
      <% if @section_title %>
        <% if @image_title %>
          <%= image_tag("#{@image_title}", style: "width: 30px; height: 30px; margin-right: 7px;") %>
        <% end %>
        <p class="navbar-title"><%= @section_title %></p>
      <% end %>
    </div>

    <%# SEARCH ICON %>
    <% if @search %>
      <%= link_to search_path do %>
        <%= image_tag('search.png') %>
      <% end %>
    <% elsif @filtros %>
      <% if params[:controller] == "horses" %>
        <%= link_to horses_filtros_path do %>
          <%= image_tag('filtros.png') %>
        <% end %>
      <% else %>
        <%= image_tag('filtros.png') %>
      <% end %>

    <%# SHARE ICON %>
    <% elsif @share_like %>
      <div class="d-flex justify-content-center align-items-center">
          <%= button_to favorite_horse_text(@horse), favorite_horse_path(horse: @horse), class: "horse_heart mx-2", remote: true %>
          <%# <div data-controller="share" data-share-url-value="<%= horse_show_path(@horse)"> %>
            <%#= button_to image_tag('share-white.svg'), "", data: {action: "click->share#share"}, style: "border: none; background: none; padding-bottom: 5px;" %>
            <%#= content_tag(:span, "", class:"result", data: {
              share_target: "result"
            }) %>
          <%# </div> %>
      </div>

    <%# DOTS ICON %>
    <% elsif @dots %>
      <div>
        <%= link_to conversacion_destroy_path, data: {"turbo-method": :delete} do %>
          <i class="fa-solid fa-trash" style="color: white; margin-right: 5px;"></i>
        <% end %>
        <% if @conversation.archive == false %>
          <%= link_to conversacion_archivar_path(@conversation.id), data: {"turbo-method": :put} do %>
            <i class="fa-solid fa-inbox" style="color: white;"></i>
          <% end %>
        <% else %>
          <%= link_to conversacion_desarchivar_path(@conversation.id), data: {"turbo-method": :put} do %>
            <i class="fa-solid fa-inbox" style="color: white;"></i>
          <% end %>
        <% end %>
      </div>

      <%# DROPDOWN NOT WORKING CORRECTLY %>
      <%# <div class="dropdown"> %>
        <%#= image_tag('dots.svg', class: "dropdown-toggle", data: {toggle: "dropdown"}, id: "dropdownMenuButton", aria: {haspopup: "true", expanded:"false"}) %>
        <%# <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="left: -140px; padding: 0;"> %>
          <%# <ul style="padding: 8px; margin-bottom: 0; text-align: center;"> %>
            <%# <li> %>
              <%#= link_to "Eliminar", conversacion_destroy_path, class: "dropdown-item", data: {"turbo-method": :delete} %>
            <%# </li> %>
            <%# <% if @conversation.archive == false %>
              <%# <li> %>
                <%#= link_to "Archivar", conversacion_archivar_path(@conversation.id), data: {"turbo-method": :put}, class: "dropdown-item" %>
              <%# </li> %>
            <%# else %>
              <%# <li> %>
                <%#= link_to "Desarchivar", conversacion_desarchivar_path(@conversation.id), data: {"turbo-method": :put}, class: "dropdown-item" %>
              <%# </li> %>
            <%# end %>
          <%# </ul> %>
        <%# </div> %>
      <%# </div> %>
    <% end %>
  </div>
</div>